---
title: "Poke Map"
output: html_document
date: "2025-08-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidygeocoder)
library(dplyr)
library(leaflet)
map_data <- read.csv("C:/Users/kasek/Documents/My-Map/Data/Vending.csv")

```



```{r}
leaflet(map_data) %>%
  addTiles() %>%
  addCircleMarkers(lng = ~Longitude, lat = ~Latitude, 1, popup = ~Address)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



<!-- --- -->
<!-- title: "Stephanie's Housing Request" -->
<!-- output:  -->
<!--   html_document: -->
<!--     theme: cerulean -->
<!--     code_folding: hide -->
<!--     toc: true -->
<!--     toc_float: true -->
<!-- --- -->



<!-- ```{r, message=FALSE, warning=FALSE} -->
<!-- library(mosaic) -->
<!-- library(tidyverse) -->
<!-- library(leaflet) -->
<!-- library(pander) -->
<!-- library(DT) # If you get an error stating:  -->
<!--             # Error in library(DT): there is no package called 'DT' -->
<!--             # You will need to run: install.packages("DT")  -->
<!--             # in your Console, then try "Knit HTML" again. -->
<!-- Rent <- read_csv("../Data/Rent.csv") -->


<!-- ```{r} -->
<!-- # Code to get you started, be sure to use a subset of Rent instead of Rent in this code though. -->
<!-- clean_women_housing <- filter(Rent, Gender=="F") -->
<!-- clean_women_housing <- select(clean_women_housing, c(Name, AvgFloorPlanCost, Residents, WebAddress) ) -->
<!-- datatable(clean_women_housing, options=list(lengthMenu = c(5,10,30)), extensions="Responsive") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- women_housing <- filter(Rent, Gender=="F") -->

<!-- ggplot(women_housing) + -->
<!--   geom_histogram(aes(x=AvgFloorPlanCost, fill = AvgFloorPlanCost < 1000), colour = "black",bins = 13) + theme_minimal()+ labs( x="Average Floor Plan Cost", y="Count", title="11 of the Apartment Complexes \nCost Less Than $1000 per Semester", fill = "Average Floor Plan\n Less Than $1000") -->



